### ISSUE TITLE
doesn't work with linux mint 18

### ISSUE THREAD

**Issue by efernbach** [Cobinja/CobiAnalogClock#11]
tried to add desklet in fresh linux mint 18 cinnamon 64bi install, 
result in the log file
error t=2016-07-03T16:15:09.242Z [Desklet "analog-clock@cobinja.de"]: Error importing desklet.js from analog-clock@cobinja.de
error t=2016-07-03T16:15:09.243Z Could not load desklet analog-clock@cobinja.de

**Comment by Cobinja** [comment]
Quote from https://cinnamon-spices.linuxmint.com/desklets/view/7:

> Note:  Make sure you have the package gir1.2-rsvg-2.0 installed

**Comment by Cobinja** [comment]
Version 2.0 is available from cinnamon settings and comes without the dependency for Rsvg.
