### ISSUE TITLE
Desktop possition lost

### ISSUE THREAD

**Issue by jorgenqv** [Cobinja/CobiAnalogClock#6]
Hello,
The clock moves to the upper left corner of the desktop when I reboot or logout and login again.
Running Mint 17.1 Cinnamon  2.4.6.

**Comment by Cobinja** [comment]
Is that the whole desklet with decorations or do the decorations stay at the original position and the clock itself moves? Can you provide a screenshot and the log from Looking Glass?

**Comment by jorgenqv** [comment]
Yes it was the whole desklet including the clock. Tried cinnemon-looking-glass and didn't figure out how to use it, but did a Reset Cinnamon Settings there and that seems to fixed things. Thanks!

**Comment by Cobinja** [comment]
If the whole desklet including decorations changes its position, then the desklet itself can't do anything about it. The positioning is done by Cinnamon
