### ISSUE TITLE
Pure cultter

### ISSUE THREAD

**Issue by lestcape** [Cobinja/CobiAnalogClock#8]
Has you some inconvenience to use pure clutter?
https://developer.gnome.org/clutter/stable/ClutterActor.html#clutter-actor-set-rotation-angle

See the implementation of GradientSelector class, as a pull of clutter actors (i.e. the hands of your watch):
https://github.com/lestcape/Color-Chooser/blob/master/colorChooser%40lestcape/colorChooser.js

**Comment by Cobinja** [comment]
I tried doing that, but the problem was that I would have to render the Svg first and then rotate. It just doesn't look good.

**Comment by lestcape** [comment]
Well i don't know what occurs before. Right now the render of an image, not need the Cutter TextureCache, you can use Gl texture to directly call gl, for an a real image using a pixbuf.

I'm never load a real image yet, but i generate an image using an integer data the spectrum of colors and a 2D gradient in Color to Black and Color to White to dynamically set this when a color change and i don't see lags.. Rendering the svg in your case only will be one time in the begin, then you only need change the angle...

**Comment by lestcape** [comment]
What you was doing probably was render all clock componentes(paint all) again and again while a seconds... I don't say this, because this is ultra slow... What i say is separate the clock components in different actors (paint or load the images only one time). Then construct the clock with all this actors one behind another in a "pool" of clutter actors. In this case you only need to change the angle or your rotation one time per seconds. Not paint anything in cairo or texturecache or cogl...

**Comment by lestcape** [comment]
Thanks. This is what i say: https://github.com/Cobinja/CobiAnalogClock/commit/35c5f7a602d95c70f3011e0547e894490af10b40

**Comment by Cobinja** [comment]
I didn't look into GdkPixbuf too much when doing it now, but it looks better than it did when I tried the first time. It seems to me that they changed the rendering process themselves, so that rotated images from svg look better.

**Comment by lestcape** [comment]
@Cobinja i don't know before, when i tell you is because i test it and for me have a good performance...  Cogl texture is a relative new way, probably this is the improve...

Anyway, is good now for my point of view i think for you to and that's what should matter.
Thanks.

**Comment by Cobinja** [comment]
If it hadn't been good from my point of view, I wouldn't have shipped

**Comment by lestcape** [comment]
:) of course.
